### ISSUE TITLE
User.validatePassword throws uncaught exception in User.create

### ISSUE THREAD

**Issue by cleas** [strongloop/loopback#1364]
related to #941 

Creating user with empty password : loopback@2.8 user created , loopback@2.9 application crash due to uncaught exception

```
User.create({username: 'John', email: 'john@doe.com', password:''},function(err,user){
//invalid password error should be returned in callback
 });
```

overriding validatePassword to check for minimum length will also give uncaught exception

see also example https://github.com/cleas/loopback-sandbox
https://github.com/cleas/loopback-sandbox/blob/master/server/boot/create-model-instances.js

**Comment by superkhau** [comment]
I tried running your example. I get:

```
Error: Invalid password:
  ...
```

Can I close this?

**Comment by cleas** [comment]
I tried with loopback 2.18.0 => error is still there.
looking at the source nothing changed to User.hashPassword and User.validatePassword.
function User.ValidatePassword can throw exception , this exception is not handled in UserModel.setter.password

**Comment by rawrmaan** [comment]
I'm having this issue as well. I overrode validatePassword in my own User model subclass and used the default implementation as a reference. Now my instance crashes whenever there's an invalid password. Should I just return false instead of throwing an error?

**Comment by jlvdh** [comment]
I also encountered this, and used the following as a quickfix in user.js

    User.observe('before save', function checkEmptyPasswordString(ctx, next) {
      if (ctx.data && ctx.data.password === '') {
        next('Password is empty string');
      }
      next();
    });

**Comment by superkhau** [comment]
@cleas Are you still running into issues? Seems to be fix by #941 now as I can't reproduce the error in your `loopback-sandbox` for anymore.

**Comment by jlvdh** [comment]
I'm still experiencing the error on Loopback 2.21.0 with the following request:

    PUT /user

    {"id":140, "password":""}

**Comment by cleas** [comment]
The error in the ````loopback-sandbox example```` is now catched due to the changes in commit: 

https://github.com/strongloop/loopback-datasource-juggler/commit/21c0067462f48210f156bb043cb4076e979ff94d
"Report deferred exceptions via callback"

But still  validatePassword exceptions are not caught in User.create function it self and returned in cb.
For example if the create functions are wrapped in a dataSource.autoupdate function, the  application crashes.
see updated ````loopback-sandbox```` example.

**Comment by gunjpan** [comment]
@cleas: I believe this should have been resolved in newer versions of LoopBack. Could you please confirm?

**Comment by vijay22sai** [comment]
Getting this error. while creation of user, it catches if there is any error. but, if i use updateAttributes function, throwing an uncaught exception. Can someone help?

**Comment by Allan1** [comment]
When calling User.updateAttribute('password','someinvalidpassword',cb), User.validatePassword() exception is not passed to the callback, thus the application crashes.
Using loopback@2.38.3

**Comment by rashmihunt** [comment]
Marking as P1 since many community members are still seeing this issue.

**Comment by dhmlau** [comment]
might be related to: https://github.com/strongloop/loopback/issues/251

**Comment by dhmlau** [comment]
I'm not sure if this is still an issue.  Using `loopback@2.38.24`, if i set the password to empty string, the error code is `INVALID_PASSWORD`.  

Here is what I've tried:
boot/test.js:
```
module.exports = function(app) {
  var user = app.models.User;
  user.create({email: 'aa@ca.ibm.com', password: ''}, (err, result)=> {
    if (err) {
      console.log('err.code = ', err.code);
      console.log(err);
    }
    console.log('result = ', result);
  });
};
```

Output:
```
err.code =  INVALID_PASSWORD
{ [Error: Invalid password: ] code: 'INVALID_PASSWORD', statusCode: 422 }
```

**Comment by loay** [comment]
Issue is fixed for all Loopback 2.x.x versions.
