### ISSUE TITLE
How can i check one property exists in mongodb collection by loopback model methods ?

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback#924]
How can i check one property exists in mongodb collection by loopback model methods ?
This is describle by document below:
http://docs.mongodb.org/manual/reference/operator/query/exists/

**Comment by raymondfeng** [comment]
Can you try?
```
{
  where: {
    myProp: {
      $exist: true
    }
  }
}
```

**Comment by dennisaj** [comment]
+1 - exist, $exist, exists are not available

**Comment by bluestaralone** [comment]
:+1:

**Comment by marcellodesales** [comment]
+1 PLEASE!!!!

Today I needed to return the list of categories/subcategories...

```
{
  "name": "category",
  "plural": "categories",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "subcategories": {
      "type": "hasMany",
      "model": "category",
      "foreignKey": "parentId"
    }
  },
  "acls": [],
  "methods": []
}
```

I want to return only all the categories in the root of the response, all all their related subcategories as the embedded object in the overridden method "find"... 

```
module.exports = function(Category) {
  Category.on('attached', function() {
    var overridden = Category.find;
    Category.find = function(filter, callback) {
      filter = filter || {};
      filter.include = 'subcategories';
      filter.where = {
        parentId: null
      };
      arguments[0] = filter;
      return overridden.apply(this, arguments);
    };
  });
};
```

Since the objects does not have the property, the query DOES NOT RETURN!!! Just like it is defined, MongoDB has this http://stackoverflow.com/questions/5719408/mongo-find-items-that-dont-have-a-certain-field

Without the wrong "where" above, I can get all the values, but the Subcategories are also returned in the root of the list :(

```
[
  {
    "name": "Category 1",
    "id": 1,
    "subcategories": [
      {
        "name": "Sub 1.1",
        "id": 3,
        "parentId": 1,
        "subcategories": []
      },
      {
        "name": "Sub 1.2",
        "id": 4,
        "parentId": 1,
        "subcategories": []
      }
    ]
  },
  {
    "name": "Category 2",
    "id": 2,
    "subcategories": []
  },
  {
    "name": "Sub 1.1",
    "id": 3,
    "parentId": 1,
    "subcategories": []
  },
  {
    "name": "Sub 1.2",
    "id": 4,
    "parentId": 1,
    "subcategories": []
  }
]
```

**Comment by Terekhov** [comment]
Looks like this is planned #1009

**Comment by jsheely** [comment]
@dennisaj Spread a little fud. This feature actually already works. See my note on the related article #1009 

exists is not explicitly available but the condition will be evaluated by automatically adding $ to in the mongodb connector.

**Comment by kashifeqbal** [comment]
```
// URL
// /api/<modelName>?filter[where][<propertyName>][exists]=<true|false>

modelName.find({
    where: {
        propertyName: {
            exists: true
        }
    }
}, callback)
```
[loopback-connector-mongodb](https://github.com/strongloop/loopback-connector-mongodb) append $ to any property which is not define in the [loopback-connector-mongodb](https://github.com/strongloop/loopback-connector-mongodb). So it will the $exists: true to the mongo database.

**Comment by loay** [comment]
@bluestaralone 
is this issue resolved using the suggestion in the previous comments?

**Comment by jdhrivas** [comment]
this issue is resolved. I tested this afternoon, and both true and false options return the desired output

**Comment by Cyperwu** [comment]
If I declare a property "a" in model definition json file, when i query
`
modelName.find({
    where: {
        a: {
            exists: true | false
        }
    }
}, callback)
`
neither `true` nor `false`  will return any result

**Comment by favour-nerrise** [comment]
@Cyperwu Try this: 
modelName.find({ fields: { a: true || false } }, callback)
It returns an array of instances where the property exists or not.

**Comment by Cyperwu** [comment]
@favour-nerrise Isn't `fields` filter used to include or exclude some property?

**Comment by favour-nerrise** [comment]
@Cyperwu Yeah, in this case it returns an array of objects [{a:....}, {a:....}] whereby the value of a is undefined or populated.

**Comment by Cyperwu** [comment]
@favour-nerrise that's a pretty cool hack but not a right way to fix this bug lol

**Comment by favour-nerrise** [comment]
@Cyperwu True; I just suggested a temporary workaround since I faced a similar issue.

**Comment by jdhrivas** [comment]
@Cyperwu I may be able to help you, can you describe what you are trying to accomplish? In my case I implemented soft deletes, by adding a new property to the model call "archived" with the value of true. Then I overwrote the "find" method by modifying the query with this:
`
query.where = { and: [ query.where, { or: [{[o.archived]: false}, {[o.archived]: null}, { [o.archived]: { exists: false } }] } ] }


`

**Comment by Cyperwu** [comment]
@favour-nerrise no... it didn't fix mine... Anyway, thanks!

**Comment by Cyperwu** [comment]
@jdhrivas I tried to find data without certain key(s) but if I defined that key in model definition JSON file, then the `exists: true | false` filter will return me nothing

**Comment by HugoPoi** [comment]
Still an issue there.
To reproduce
1. Create a model with an optional `property` stored with mongodb-connector
1. Create a instance of this model without the property
1. `Model.find({ filter: { where: { property: { exists: false } } } })` => this return nothing
1. Remove the declared optional property and it works

This is due to mongodb-connector parsing the filter.

**Comment by akvaliya** [comment]
I am also getting this issue.
Works for exists:true, but doesn't work for exists:false

**Comment by F3L1X79** [comment]
Still having the issue in 2018

**Comment by frankorama** [comment]
**This is what worked for me:**

I have a date property that is not required.  I want to fetch objects that either don't have a date or, if they do have a date, the date is today:

```
"where": {
  or:[
    {workDate: {between:[startOfDay.format(),endOfDay.format()]} },
    {workDate: undefined}
  ]
}
```

**_Details:_**
Loopback 2
tried `exists`, `$exists`, `exist`, `$exist`, and `workDate: null`, but nothing worked.  Only `undefined` worked for me

**Comment by frankorama** [comment]
This is still an issue for me.  I have a date field that is not required and I want to fetch documents that have a date of today or no date:

```
where: {
  or: [
    {workDate: {between: [startDate, endDate]}},
    <not set clause>
  ],  
},
```

for the `<not set clause>` I have tried the following:
`{workDate:{exists: false}}` => bad date format
`{workDate:{$exists: false}}` => bad date format
`{workDate:{exist: false}}` => bad date format
`{workDate:{$exist: false}}` => bad date format
`{workDate:null}` => does not return documents with no field
`{workDate:undefined}` => does not return documents with no field

**Comment by kjdelisle** [comment]
@frankorama @sivicencio 

If someone would like to open an issue [here](https://github.com/strongloop/loopback-connector-mongodb/issues) with a reproduction sandbox (a small toy app that demonstrates the problem) then we can triage the issue and find the source of the problem. Ping me in the issue and I'll tag it accordingly.

**Comment by mrbatista** [comment]
@kjdelisle Please see issue https://github.com/strongloop/strong-remoting/issues/443 for more details. The problem is related to strong-remoting.

**Comment by jdhrivas** [comment]
@frankorama @sivicencio make sure you set "allowExtendedOperators": true in your mongo datasource.json file.
also the syntax is 
```
{ where: { notExistingProperty: { exists: false } } }
```

**Comment by shubhamsingh2209** [comment]
> This is still an issue for me. I have a date field that is not required and I want to fetch documents that have a date of today or no date:
> 
> ```
> where: {
>   or: [
>     {workDate: {between: [startDate, endDate]}},
>     <not set clause>
>   ],  
> },
> ```
> 
> for the `<not set clause>` I have tried the following:
> `{workDate:{exists: false}}` => bad date format
> `{workDate:{$exists: false}}` => bad date format
> `{workDate:{exist: false}}` => bad date format
> `{workDate:{$exist: false}}` => bad date format
> `{workDate:null}` => does not return documents with no field
> `{workDate:undefined}` => does not return documents with no field



> This is still an issue for me. I have a date field that is not required and I want to fetch documents that have a date of today or no date:
> 
> ```
> where: {
>   or: [
>     {workDate: {between: [startDate, endDate]}},
>     <not set clause>
>   ],  
> },
> ```
> 
> for the `<not set clause>` I have tried the following:
> `{workDate:{exists: false}}` => bad date format
> `{workDate:{$exists: false}}` => bad date format
> `{workDate:{exist: false}}` => bad date format
> `{workDate:{$exist: false}}` => bad date format
> `{workDate:null}` => does not return documents with no field
> `{workDate:undefined}` => does not return documents with no field

Hi ,
I have also faced this issue and find something by which it will solve out this issue.

Actually exists is not a built-in operator, it's MongoDB specific. To use a database-specific operator, you need to prefix it with $, e.g. $exists.

Models.find({
        where: {
            read_at: {
                $exists: false
            }
        }
    }

Steps to resolve:-
"allowExtendedOperators": true
You need to enable this feature via model settings (on a per-model basis) or datasource settings (for all models attached to the datasource).
Eg.
{
  "name": "messages",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true,
    "strictObjectIDCoercion": false,
    "allowExtendedOperators": true
  },

Hope this will solve this issue.

**Comment by canmustu** [comment]
> @frankorama @sivicencio make sure you set "allowExtendedOperators": true in your mongo datasource.json file. also the syntax is
> 
> ```
> { where: { notExistingProperty: { exists: false } } }
> ```

From 2024, this worked for me. Thanks..!
